blank_issues_enabled: true
contact_links:
  - name: Helbreath Xtreme Support
    url: https://forum.helbreathx.net/support
    about: Contact Support if you're having trouble with your Helbreath Xtreme account.
